# Generated by Django 4.0.3 on 2022-03-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_account1_post1_remove_post_user_delete_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('handle', models.CharField(max_length=200, null=True)),
                ('profileImage', models.ImageField(blank=True, height_field=60, null=True, upload_to='', width_field=60)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Posted')),
                ('description', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('comments', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(blank=True, height_field=600, null=True, upload_to='', width_field=340)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='post1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account1',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
