# Generated by Django 4.0.3 on 2022-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_user_post_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
