# Generated by Django 4.0.3 on 2022-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profileImage',
        ),
    ]
