# Generated by Django 4.0.3 on 2022-03-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
