# Generated by Django 4.0.3 on 2022-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_account_profileimage_post_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
